# Generated by Django 5.2.13 on 2026-04-15 15:35

import html

from django.db import migrations, models
from django.utils.text import Truncator


DEFAULT_BLOG_AUTHOR = "Finora UAE Editorial Team"


def _paragraphs_to_html(raw_content):
    if isinstance(raw_content, (list, tuple)):
        paragraphs = [str(item).strip() for item in raw_content if str(item).strip()]
    elif isinstance(raw_content, str) and raw_content.strip():
        paragraphs = [raw_content.strip()]
    else:
        paragraphs = []

    return "".join(f"<p>{html.escape(paragraph)}</p>" for paragraph in paragraphs)


def migrate_blog_content_and_seo(apps, schema_editor):
    BlogPost = apps.get_model("finoraapp", "BlogPost")

    for post in BlogPost.objects.all():
        post.content_html = _paragraphs_to_html(post.content)
        post.author_name = post.author_name or DEFAULT_BLOG_AUTHOR
        post.meta_title = post.meta_title or post.title
        post.meta_description = post.meta_description or Truncator(post.excerpt).chars(160)
        post.save(
            update_fields=(
                "content_html",
                "author_name",
                "meta_title",
                "meta_description",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("finoraapp", "0002_seed_blog_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author_name",
            field=models.CharField(default=DEFAULT_BLOG_AUTHOR, max_length=100),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(migrate_blog_content_and_seo, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="content_html",
            new_name="content",
        ),
    ]
