# Generated by Django 5.2.13 on 2026-04-17 06:46

from datetime import date

from django.db import migrations, models


OLD_SEEDED_BLOG_SLUGS = [
    "uae-corporate-tax-guide-2026",
    "business-setup-dubai-2026",
    "vat-compliance-tips-uae",
    "financial-planning-smes-uae",
    "economic-substance-regulations",
    "audit-preparation-guide",
]

ITHIHASA_BLOG_POSTS = [
    {
        "title": "Top 5 Home Maintenance Tips Every Homeowner Should Know",
        "slug": "top-5-home-maintenance-tips",
        "excerpt": "Regular home maintenance prevents costly repairs. Here are 5 essential tips to keep your home in top shape year-round.",
        "category": "Home Tips",
        "cover_image": "blog-header",
        "content": """
            <h2>1. Schedule Regular HVAC Maintenance</h2>
            <p>Your heating and cooling system works hard year-round. Schedule professional servicing at least twice a year to keep it running efficiently and extend its lifespan.</p>
            <h2>2. Check for Water Leaks Monthly</h2>
            <p>A small leak can lead to major damage. Inspect under sinks, around toilets, and near water heaters monthly. Early detection saves thousands in repairs.</p>
            <h2>3. Clean Gutters and Drains</h2>
            <p>Clogged gutters cause water damage to your roof and foundation. Clean them at least twice a year, especially before monsoon season.</p>
            <h2>4. Test Smoke Detectors and Electrical Safety</h2>
            <p>Replace batteries in smoke detectors annually. Check for frayed wires, overloaded circuits, and ensure your MCB panel is functioning properly.</p>
            <h2>5. Repaint and Seal Exterior Surfaces</h2>
            <p>Exterior paint does more than look good. It protects your home from weather damage. Touch up peeling areas and reseal windows and doors annually.</p>
            <h2>Conclusion</h2>
            <p>A little preventive maintenance goes a long way. Book Ithihasa's annual home maintenance package for peace of mind.</p>
        """.strip(),
        "author_name": "Ithihasa Team",
        "meta_title": "Top 5 Home Maintenance Tips Every Homeowner Should Know",
        "meta_description": "Regular home maintenance prevents costly repairs. Explore five practical tips every homeowner should follow year-round.",
        "read_time_minutes": 5,
        "published_at": date(2026, 4, 5),
        "featured": True,
        "is_published": True,
    },
    {
        "title": "How to Choose the Right Paint Colors for Your Home",
        "slug": "choosing-right-paint-colors",
        "excerpt": "Selecting paint colors can be overwhelming. Our expert guide helps you pick the perfect palette for every room.",
        "category": "Painting",
        "cover_image": "banner-painting",
        "content": """
            <h2>Understanding Color Psychology</h2>
            <p>Colors affect mood and energy. Cool blues and greens create calm spaces perfect for bedrooms, while warm yellows and oranges energize kitchens and living areas.</p>
            <h2>Consider Natural Light</h2>
            <p>Rooms with lots of natural light can handle darker shades. North-facing rooms benefit from warm tones to counteract cool light.</p>
            <h2>The 60-30-10 Rule</h2>
            <p>Use 60% dominant color for walls, 30% secondary color for furniture and curtains, and 10% accent color for decor.</p>
            <h2>Test Before You Commit</h2>
            <p>Always test paint samples on your actual walls. Colors look different under your home's specific lighting conditions.</p>
            <h2>Popular Trends for 2026</h2>
            <p>Earth tones, sage greens, and warm terracotta are trending this year. Matte finishes continue to be popular for living spaces.</p>
            <p>Book a free color consultation with Ithihasa's painting experts if you need help choosing the final palette.</p>
        """.strip(),
        "author_name": "Design Team",
        "meta_title": "How to Choose the Right Paint Colors for Your Home",
        "meta_description": "Learn how to choose paint colors that match your home, lighting, and mood with Ithihasa's practical color guide.",
        "read_time_minutes": 6,
        "published_at": date(2026, 3, 28),
        "featured": False,
        "is_published": True,
    },
    {
        "title": "Smart Home Setup: A Beginner's Complete Guide",
        "slug": "smart-home-beginners-guide",
        "excerpt": "Transform your home with smart technology. From lighting to security, here's everything you need to know to get started.",
        "category": "Smart Home",
        "cover_image": "banner-smarthome",
        "content": """
            <h2>What is a Smart Home?</h2>
            <p>A smart home uses internet-connected devices to allow remote management of appliances, lighting, security, and temperature.</p>
            <h2>Start with Smart Lighting</h2>
            <p>Smart bulbs are the easiest entry point. Control brightness, color, and schedules from your phone or voice assistant.</p>
            <h2>Add Security Next</h2>
            <p>Smart locks, video doorbells, and CCTV cameras provide peace of mind. Most systems send real-time alerts to your phone.</p>
            <h2>Voice Assistants</h2>
            <p>Amazon Alexa or Google Home can act as the brain of your smart home and connect your devices into one routine.</p>
            <h2>Wi-Fi is Key</h2>
            <p>A strong, reliable Wi-Fi network is essential. Consider mesh routers for larger homes so coverage reaches every room.</p>
            <p>Book Ithihasa's smart home setup service for a hassle-free installation and seamless integration.</p>
        """.strip(),
        "author_name": "Tech Team",
        "meta_title": "Smart Home Setup: A Beginner's Complete Guide",
        "meta_description": "Start building a smart home with confidence using this beginner-friendly guide from Ithihasa's smart home experts.",
        "read_time_minutes": 6,
        "published_at": date(2026, 3, 15),
        "featured": False,
        "is_published": True,
    },
]


def seed_ithihasa_blog_posts(apps, schema_editor):
    BlogPost = apps.get_model("finoraapp", "BlogPost")

    BlogPost.objects.filter(slug__in=OLD_SEEDED_BLOG_SLUGS).update(is_published=False)

    for entry in ITHIHASA_BLOG_POSTS:
        BlogPost.objects.update_or_create(
            slug=entry["slug"],
            defaults=entry,
        )


def fill_contact_subjects(apps, schema_editor):
    ContactSubmission = apps.get_model("finoraapp", "ContactSubmission")

    for submission in ContactSubmission.objects.all():
        if not submission.subject:
            city = submission.city or "your area"
            service = submission.service or "General enquiry"
            submission.subject = f"New {service} booking in {city}"
            submission.save(update_fields=["subject"])


class Migration(migrations.Migration):

    dependencies = [
        ('finoraapp', '0003_blogpost_rich_content_and_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Ithihasa Editorial Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(fill_contact_subjects, migrations.RunPython.noop),
        migrations.RunPython(seed_ithihasa_blog_posts, migrations.RunPython.noop),
    ]
