# Generated by Django 5.2.13 on 2026-04-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finoraapp', '0004_contactsubmission_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, default='', upload_to='blog/covers/'),
        ),
    ]
