# Generated by Django 5.2.13 on 2026-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finoraapp', '0007_rename_brand_to_itihasam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Itihasam Editorial Team', max_length=100),
        ),
    ]
